name: context-contrasting
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.11
  - matplotlib
  - numpy
  - pandas
  - seaborn
  - pytorch>=2.5,<2.6
  - joblib
  - tqdm
  - scikit-learn
  - sbi
  - pip
  - pip:
      - -e .
